# Generated by Django 2.1.7 on 2020-07-16 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('max_charges', models.IntegerField()),
                ('recharge_cooldown', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('champion_option', models.CharField(choices=[('value1', 'value1')], max_length=200, null=True)),
                ('ability_e1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability_e1', to='champions.Ability')),
                ('ability_e2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability_e2', to='champions.Ability')),
                ('ability_q1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability_q1', to='champions.Ability')),
                ('ability_q2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability_q2', to='champions.Ability')),
                ('ability_r1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability_r1', to='champions.Ability')),
                ('ability_r2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability_r2', to='champions.Ability')),
                ('ability_w1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability_w1', to='champions.Ability')),
                ('ability_w2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability_w2', to='champions.Ability')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank1', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rank2', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rank3', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rank4', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rank5', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('is_percentage', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank1', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rank2', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rank3', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rank4', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rank5', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='EffectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('is_percentage', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Indoor', 'Indoor'), ('Out Door', 'Out Door')], max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scaling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank1', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rank2', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rank3', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rank4', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rank5', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScalingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('is_percentage', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='scaling',
            name='scaling_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling_type', to='champions.ScalingType'),
        ),
        migrations.AddField(
            model_name='effect',
            name='effect_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_type', to='champions.EffectType'),
        ),
        migrations.AddField(
            model_name='effect',
            name='scaling_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling_1', to='champions.Scaling'),
        ),
        migrations.AddField(
            model_name='effect',
            name='scaling_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling_2', to='champions.Scaling'),
        ),
        migrations.AddField(
            model_name='cost',
            name='cost_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_type', to='champions.CostType'),
        ),
        migrations.AddField(
            model_name='ability',
            name='cost1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_1', to='champions.Cost'),
        ),
        migrations.AddField(
            model_name='ability',
            name='cost2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_2', to='champions.Cost'),
        ),
        migrations.AddField(
            model_name='ability',
            name='effect1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_1', to='champions.Effect'),
        ),
        migrations.AddField(
            model_name='ability',
            name='effect2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_2', to='champions.Effect'),
        ),
        migrations.AddField(
            model_name='ability',
            name='effect3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_3', to='champions.Effect'),
        ),
        migrations.AddField(
            model_name='ability',
            name='effect4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_4', to='champions.Effect'),
        ),
        migrations.AddField(
            model_name='ability',
            name='effect5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_5', to='champions.Effect'),
        ),
        migrations.AddField(
            model_name='ability',
            name='effect6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_6', to='champions.Effect'),
        ),
        migrations.AddField(
            model_name='ability',
            name='effect7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_7', to='champions.Effect'),
        ),
        migrations.AddField(
            model_name='ability',
            name='effect8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_8', to='champions.Effect'),
        ),
        migrations.AddField(
            model_name='ability',
            name='effect9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_9', to='champions.Effect'),
        ),
    ]
