# Generated by Django 2.1.7 on 2020-07-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0004_auto_20200717_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='champion_option',
        ),
    ]
