# Generated by Django 2.1.7 on 2020-07-17 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0005_remove_champion_champion_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='champion',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_type', to='champions.CostType', unique=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='effect_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='effect_type', to='champions.EffectType', unique=True),
        ),
        migrations.AlterField(
            model_name='scaling',
            name='scaling_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scaling_type', to='champions.ScalingType', unique=True),
        ),
    ]
