# Generated by Django 2.1.7 on 2020-07-17 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0006_auto_20200717_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='cost_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_type', to='champions.CostType'),
        ),
        migrations.AlterField(
            model_name='costtype',
            name='description',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='effect_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='effect_type', to='champions.EffectType'),
        ),
        migrations.AlterField(
            model_name='effecttype',
            name='description',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='scaling',
            name='scaling_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scaling_type', to='champions.ScalingType'),
        ),
        migrations.AlterField(
            model_name='scalingtype',
            name='description',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
