# Generated by Django 2.1.7 on 2020-07-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0007_auto_20200717_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='name',
        ),
    ]
