# Generated by Django 2.1.7 on 2020-07-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0009_auto_20200717_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='armor',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='champion',
            name='armor_scaling',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='champion',
            name='attack_damage',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='champion',
            name='attack_damage_scaling',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='champion',
            name='attack_speed',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='champion',
            name='attack_speed_scaling',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='champion',
            name='health',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='champion',
            name='health_regen',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='champion',
            name='health_regen_scaling',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='champion',
            name='health_scaling',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='champion',
            name='magic_resist',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='champion',
            name='magic_resist_scaling',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='champion',
            name='mana',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='champion',
            name='mana_regen',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='champion',
            name='mana_regen_scaling',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='champion',
            name='mana_scaling',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='champion',
            name='movement_speed',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='champion',
            name='range',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ability',
            name='cooldown_rank1',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ability',
            name='cooldown_rank2',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ability',
            name='cooldown_rank3',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ability',
            name='cooldown_rank4',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ability',
            name='cooldown_rank5',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ability',
            name='recharge_cooldown_rank1',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ability',
            name='recharge_cooldown_rank2',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ability',
            name='recharge_cooldown_rank3',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ability',
            name='recharge_cooldown_rank4',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ability',
            name='recharge_cooldown_rank5',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cost',
            name='rank1',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cost',
            name='rank2',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cost',
            name='rank3',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cost',
            name='rank4',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cost',
            name='rank5',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='effect',
            name='rank1',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='effect',
            name='rank2',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='effect',
            name='rank3',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='effect',
            name='rank4',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='effect',
            name='rank5',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='scaling',
            name='rank1',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='scaling',
            name='rank2',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='scaling',
            name='rank3',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='scaling',
            name='rank4',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='scaling',
            name='rank5',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
    ]
