# Generated by Django 2.1.7 on 2020-07-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0018_auto_20200717_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='cooldown_rank1',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='cooldown_rank2',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='cooldown_rank3',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='cooldown_rank4',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='cooldown_rank5',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='recharge_cooldown_rank1',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='recharge_cooldown_rank2',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='recharge_cooldown_rank3',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='recharge_cooldown_rank4',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='recharge_cooldown_rank5',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='rank1',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='rank2',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='rank3',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='rank4',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='rank5',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='rank1',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='rank2',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='rank3',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='rank4',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='rank5',
        ),
        migrations.RemoveField(
            model_name='scaling',
            name='rank1',
        ),
        migrations.RemoveField(
            model_name='scaling',
            name='rank2',
        ),
        migrations.RemoveField(
            model_name='scaling',
            name='rank3',
        ),
        migrations.RemoveField(
            model_name='scaling',
            name='rank4',
        ),
        migrations.RemoveField(
            model_name='scaling',
            name='rank5',
        ),
        migrations.AddField(
            model_name='ability',
            name='cooldown_ranks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ability',
            name='recharge_cooldown_ranks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cost',
            name='value_ranks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='value_ranks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scaling',
            name='value_ranks',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
