# Generated by Django 2.1.7 on 2020-07-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0019_auto_20200717_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='cost_type',
        ),
        migrations.RemoveField(
            model_name='scaling',
            name='scaling_type',
        ),
        migrations.RenameField(
            model_name='effect',
            old_name='value_ranks',
            new_name='effect_ranks',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='cost1',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='cost2',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='scaling_1',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='scaling_2',
        ),
        migrations.AddField(
            model_name='ability',
            name='cost2_ranks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ability',
            name='cost2_type',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ability',
            name='cost_ranks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ability',
            name='cost_type',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='scaling2_ranks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='scaling2_type',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='scaling_ranks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='scaling_type',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='effect_type',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
        migrations.DeleteModel(
            name='CostType',
        ),
        migrations.DeleteModel(
            name='EffectType',
        ),
        migrations.DeleteModel(
            name='Scaling',
        ),
        migrations.DeleteModel(
            name='ScalingType',
        ),
    ]
