# Generated by Django 2.1.7 on 2020-07-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0022_auto_20200718_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costtype',
            name='is_percentage',
        ),
        migrations.RemoveField(
            model_name='effecttype',
            name='is_percentage',
        ),
        migrations.RemoveField(
            model_name='scalingtype',
            name='is_percentage',
        ),
    ]
