# Generated by Django 2.1.7 on 2020-07-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0023_auto_20200718_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='max_charges',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='max_stacks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
