# Generated by Django 2.1.7 on 2020-07-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0024_auto_20200718_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
