# Generated by Django 2.1.7 on 2020-07-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0025_auto_20200718_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='effect_champion_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
