# Generated by Django 2.1.7 on 2020-07-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0026_effect_effect_champion_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effect',
            name='effect_champion_name',
        ),
        migrations.AddField(
            model_name='effect',
            name='effect_ability_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
