# Generated by Django 2.1.7 on 2020-07-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0027_auto_20200718_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
