# Generated by Django 2.1.7 on 2020-07-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0028_auto_20200721_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='ability_position',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
