# Generated by Django 2.1.7 on 2020-07-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0030_auto_20200724_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='ability_position',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
